/**
 * Configuration Generator - Extracted from ProjectFactory
 * Generates TOML configs, READMEs, and handles global project registration for MCP server discovery.
 */

import type { DefaultProjectConfig, ProjectConfig } from '../types/project-factory-types'
import { FileHelper } from '../utils/file-helper'

export interface ConfigGeneratorOptions { configDir: string, projectsConfigDir: string }
export interface ProjectRegistrationData {
  projectCode: string
  projectPath: string
  registered: string
  active?: boolean
}

export class ConfigurationGenerator {
  private static readonly DEFAULT_CONFIG: DefaultProjectConfig = {
    crPath: 'docs/CRs',
    documentPaths: ['docs'],
    excludeFolders: ['node_modules', '.git', 'test-results'],
  }

  constructor(private options: ConfigGeneratorOptions) {}

  generateMdtConfig(projectCode: string, projectName: string, config: ProjectConfig = {}): string {
    const finalConfig = { ...ConfigurationGenerator.DEFAULT_CONFIG, ...config }
    return `[project]
name = "${projectName}"
code = "${projectCode}"
id = "${projectCode}"
ticketsPath = "${finalConfig.crPath}"
startNumber = 1
counterFile = ".mdt-next"
${finalConfig.description ? `description = "${finalConfig.description}"\n` : ''}
${finalConfig.repository ? `repository = "${finalConfig.repository}"\n` : ''}

[project.document]
paths = [${finalConfig.documentPaths!.map(p => `"${p}"`).join(', ')}]
excludeFolders = [${finalConfig.excludeFolders!.map(p => `"${p}"`).join(', ')}]
maxDepth = 3
`
  }

  generateReadme(projectName: string, customContent?: Record<string, string>): string {
    let content = `# ${projectName}

Test project for E2E testing.

## Purpose
This project is automatically generated for testing purposes.

## Configuration
The project is configured with:
- \`.mdt-config.toml\`: MCP server configuration
- \`${ConfigurationGenerator.DEFAULT_CONFIG.crPath}\`: Directory for CR files
- \`.mdt-next\`: Counter for CR numbering`

    if (customContent) {
      Object.entries(customContent).forEach(([section, text]) => {
        content += `\n\n## ${section}\n\n${text}`
      })
    }

    return `${content}

## Testing
This project is used by the E2E test suite to verify:
- Project auto-discovery
- CR creation via MCP API
- CR management operations

---
*Generated by ConfigurationGenerator for E2E testing*`
  }

  generateProjectRegistration(data: ProjectRegistrationData): string {
    return `[project]
path = "${data.projectPath}"
code = "${data.projectCode}"
active = ${data.active !== false ? 'true' : 'false'}

[metadata]
dateRegistered = "${data.registered}"
lastAccessed = "${new Date().toISOString().split('T')[0]}"
version = "1.0.0"
`
  }

  createProjectRegistration(data: ProjectRegistrationData): string {
    const path = FileHelper.joinPath(this.options.projectsConfigDir, `${data.projectCode}.toml`)
    FileHelper.writeFile(path, this.generateProjectRegistration(data))
    return path
  }

  generateProjectConfigPackage(projectCode: string, projectName: string, config: ProjectConfig = {}, readmeCustomContent?: Record<string, string>) {
    const reg = { projectCode, projectPath: '', registered: new Date().toISOString(), active: true }
    return {
      mdtConfig: this.generateMdtConfig(projectCode, projectName, config),
      readmeContent: this.generateReadme(projectName, readmeCustomContent),
      registrationContent: this.generateProjectRegistration(reg),
    }
  }

  getDefaults(): DefaultProjectConfig {
    return { ...ConfigurationGenerator.DEFAULT_CONFIG }
  }
}
