/**
 * MDT-150: linkNormalization constraint tests
 *
 * Tests that linkNormalization remains unchanged (architecture decision:
 * resolution moved to SmartLink's resolveDocumentHref).
 *
 * Covers C3, C4 baseline behavior.
 */
import { describe, expect, it } from 'bun:test'
import { createLinkContext, LinkNormalizer } from './linkNormalization'

describe('MDT-150: linkNormalization resolution', () => {
  // Simulate a source file inside docs/CRs/MDT-150/ (a ticket subdoc)
  const ticketSubdocContext = createLinkContext({
    currentProject: 'MDT',
    sourcePath: 'docs/CRs/MDT-150/architecture.md',
  })

  describe('BR-1: .md ref resolution from ticket subdoc', () => {
    it('resolves bare .md filename from ticket subdoc', () => {
      const result = LinkNormalizer.normalizeLink('core-layout.md', ticketSubdocContext)
      expect(result.isValid).toBe(true)
      expect(result.webHref).toContain('/prj/MDT/documents')
    })

    it('resolves relative ./ path from ticket subdoc', () => {
      const result = LinkNormalizer.normalizeLink('./core-layout.md', ticketSubdocContext)
      expect(result.isValid).toBe(true)
    })
  })

  describe('BR-2: sibling ticket reference (LinkNormalizer baseline)', () => {
    it('classifies MDT-151.md as a ticket link', () => {
      // MDT-151.md matches the ticket key regex pattern
      const result = LinkNormalizer.normalizeLink('MDT-151.md', ticketSubdocContext)
      expect(result.type).toBe('ticket')
      expect(result.isValid).toBe(true)
      expect(result.webHref).toContain('/prj/MDT/ticket/MDT-151')
    })

    it('classifies MDT-151 as a ticket link (no .md)', () => {
      const result = LinkNormalizer.normalizeLink('MDT-151', ticketSubdocContext)
      expect(result.type).toBe('ticket')
      expect(result.webHref).toContain('/prj/MDT/ticket/MDT-151')
    })
  })

  describe('BR-3: anchor fragment passthrough', () => {
    it('preserves anchor on ticket reference', () => {
      const result = LinkNormalizer.normalizeLink('MDT-151#overview', ticketSubdocContext)
      expect(result.isValid).toBe(true)
      expect(result.webHref).toContain('#overview')
    })

    it('preserves anchor on .md ticket reference', () => {
      const result = LinkNormalizer.normalizeLink('MDT-151.md#section', ticketSubdocContext)
      expect(result.type).toBe('ticket')
      expect(result.webHref).toContain('#section')
    })
  })

  describe('C4: no security checks in normalization', () => {
    it('does not reject path traversal at normalization level', () => {
      // LinkNormalizer has path traversal detection, but that's input validation
      // not security enforcement. SmartLink itself must not validate existence.
      // The constraint says SmartLink must not do security checks —
      // LinkNormalizer's checks are path sanitization for routing, not security.
      const result = LinkNormalizer.normalizeLink('../etc/passwd', ticketSubdocContext)
      // Should be marked as broken due to path traversal, but this is
      // normalization-level sanitization, not SmartLink security enforcement
      expect(result.isValid).toBe(false)
    })
  })

  describe('C3: handles relative paths, bare filenames, sibling refs', () => {
    it('handles bare filename (architecture.md)', () => {
      const result = LinkNormalizer.normalizeLink('architecture.md', ticketSubdocContext)
      expect(result.isValid).toBe(true)
    })

    it('handles relative path (./subdir/file.md)', () => {
      const result = LinkNormalizer.normalizeLink('./subdir/file.md', ticketSubdocContext)
      expect(result.isValid).toBe(true)
    })
  })

  describe('C1: absolute ticket URLs from preprocessor', () => {
    it('preserves absolute ticket URL href unchanged', () => {
      // Absolute ticket URLs are generated by the preprocessor and
      // classified by linkProcessor's classifyLink, not by LinkNormalizer.
      // LinkNormalizer doesn't need to handle these — SmartLink receives
      // them already classified as TICKET type from the parser.
      const result = LinkNormalizer.normalizeLink('/prj/MDT/ticket/MDT-150', ticketSubdocContext)
      expect(result.originalHref).toBe('/prj/MDT/ticket/MDT-150')
    })

    it('does not match partial absolute paths as ticket URLs', () => {
      const result = LinkNormalizer.normalizeLink('/prj/MDT/documents/file.md', ticketSubdocContext)
      expect(result.type).not.toBe('ticket')
    })
  })

  describe('Resolution delegated to SmartLink (architecture decision)', () => {
    // These cases are handled by SmartLink's resolveDocumentHref,
    // not by LinkNormalizer. The E2E tests cover the end-to-end behavior.

    it('LinkNormalizer blocks ../../README.md (path traversal guard)', () => {
      const context = createLinkContext({
        currentProject: 'MDT',
        sourcePath: 'docs/CRs/MDT-150/architecture.md',
      })
      const result = LinkNormalizer.normalizeLink('../../README.md', context)
      // LinkNormalizer blocks this — SmartLink resolves it instead via path math
      expect(result.isValid).toBe(false)
    })

    it('LinkNormalizer blocks ../MDT-151.md (path traversal guard)', () => {
      const result = LinkNormalizer.normalizeLink('../MDT-151.md', ticketSubdocContext)
      // LinkNormalizer blocks this — SmartLink resolves it instead via ticket key detection
      expect(result.isValid).toBe(false)
    })

    it('LinkNormalizer does not recognize absolute ticket URLs', () => {
      // These are handled by classifyLink in the parser, not by LinkNormalizer
      const result = LinkNormalizer.normalizeLink('/prj/MDT/ticket/MDT-150', ticketSubdocContext)
      expect(result.type).toBe('broken')
    })

    it('LinkNormalizer does not recognize absolute cross-project URLs', () => {
      const result = LinkNormalizer.normalizeLink('/prj/OTHER/ticket/OTHER-123', ticketSubdocContext)
      expect(result.type).toBe('broken')
    })
  })
})
