/**
 * Tests for: MDT-101 - Project Test Fixtures
 * Purpose: Verify test builders create valid data
 * Generated by: /mdt:tests
 * Status: RED (implementation pending)
 */

import { ProjectFixture } from './project.fixtures';
import { ProjectSchema } from '../project/schema';

describe('Project Fixtures', () => {
  describe('ProjectFixture', () => {
    it('creates valid minimal project', () => {
      const project = ProjectFixture.minimal();
      const result = ProjectSchema.safeParse(project);
      expect(result.success).toBe(true);
    });

    it('creates valid complete project', () => {
      const project = ProjectFixture.complete();
      const result = ProjectSchema.safeParse(project);
      expect(result.success).toBe(true);
    });

    it('creates project with custom values', () => {
      const project = ProjectFixture.custom({
        id: 'custom-project',
        project: {
          name: 'Custom Project',
          active: false,
        }
      });
      const result = ProjectSchema.safeParse(project);
      expect(result.success).toBe(true);
      expect(project.id).toBe('custom-project');
      expect(project.project.name).toBe('Custom Project');
      expect(project.project.active).toBe(false);
    });

    it('generates unique projects', () => {
      const project1 = ProjectFixture.minimal();
      const project2 = ProjectFixture.minimal();

      expect(project1.id).not.toBe(project2.id);
    });

    it('creates array of projects', () => {
      const projects = ProjectFixture.array(3);
      expect(projects).toHaveLength(3);

      projects.forEach(project => {
        const result = ProjectSchema.safeParse(project);
        expect(result.success).toBe(true);
      });
    });
  });
});